version: '3.6'

services: 

  mobile:
    container_name: ws-mobile-app
    build: ./mobile
    command: npm start
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    env_file: 
      - .env.dev
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes: 
      - ./mobile:/opt/mobile
      - modules:/opt/mobile/node_modules
    networks:
      - default

volumes:
  modules:
    name: ws-node-modules

networks:
  default:
    name: ws-default
